**Download the dataset and debugging code**

In [ ]:
# Path name for dataset
train_path = 'hw4.csv'
test_path = 'hw4_testing.csv'


# Download the data 
!gdown --id '1AYRPCokkyus9klaph3Mn8LxfrFATQ3OD' --output hw4_testing.csv
!gdown --id '17Ec_qbQQKYiZdpBi8OzmuBUx_H5r2lVU' --output hw4.csv
!gdown --id '1qWkJJ9P3WZ55i9YeZ3UzDl5-8ae5EZ2P' --output pcl
!gdown --id '1QUBUfDCV5dQZqUXKwT7zWiS3qR6Kf4AZ' --output sample_submission.csv


Downloading...
From: https://drive.google.com/uc?id=1AYRPCokkyus9klaph3Mn8LxfrFATQ3OD
To: /content/hw4_testing.csv
100% 1.28k/1.28k [00:00<00:00, 933kB/s]
Downloading...
From: https://drive.google.com/uc?id=17Ec_qbQQKYiZdpBi8OzmuBUx_H5r2lVU
To: /content/hw4.csv
100% 1.53k/1.53k [00:00<00:00, 1.32MB/s]
Downloading...
From: https://drive.google.com/uc?id=1qWkJJ9P3WZ55i9YeZ3UzDl5-8ae5EZ2P
To: /content/pcl
100% 20.5M/20.5M [00:00<00:00, 26.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1QUBUfDCV5dQZqUXKwT7zWiS3qR6Kf4AZ
To: /content/sample_submission.csv
100% 236/236 [00:00<00:00, 165kB/s]


**Run this block for debuging your algorithm**

This debug code is the output of hw4_testing.csv. 

You should instead train your algorithm on hw4.csv.

That is, instead of obtaining five weights in each epoch, you should calculate six weights in each epoch.

In [ ]:
!chmod +x pcl
!./pcl 

epoch = 1, weights = 0.30 0.76 0.19 0.78 0.33
epoch = 2, weights = 0.30 0.66 0.31 0.73 0.37
epoch = 3, weights = 0.30 0.57 0.42 0.69 0.42
epoch = 4, weights = 0.50 0.64 0.33 0.56 0.44
epoch = 5, weights = 0.30 0.55 0.45 0.67 0.43
epoch = 6, weights = 0.10 0.65 0.32 0.79 0.36
epoch = 7, weights = 0.30 0.73 0.23 0.65 0.38
epoch = 8, weights = 0.30 0.63 0.35 0.61 0.43
epoch = 9, weights = 0.30 0.53 0.46 0.57 0.47
epoch = 10, weights = 0.10 0.63 0.34 0.69 0.40


**Implement your perceptron algorithm**

Implement the perceptron algorithm with following configuration

learning_rate = 0.1

number of epoch = 10

initial_weight = 0.5

In [ ]:
import numpy as np
dataset = np.genfromtxt('hw4.csv', delimiter=',')
l_rate = 0.1
n_epoch = 10
initial_weight = 0.5
print(dataset)

[[ 1.35376718 -0.73229415 -0.87210827  0.4167009   0.03419463  1.        ]
 [-0.34823046 -0.17911861 -0.36049543 -0.27048646  0.1655967  -1.        ]
 [ 0.46549712 -0.76022261 -1.75218105 -1.71012837  0.94015988 -1.        ]
 [ 0.54476608  0.08702073  0.30319383  0.455433   -0.21725465 -1.        ]
 [-0.05787224 -0.81447809 -0.5810378   1.4476303  -0.37748363  1.        ]
 [-0.28995799  1.21599171  1.94815541  0.57322546 -0.59093697  1.        ]
 [ 0.37415928  1.25029887  1.60918821 -0.40738126 -0.18676714 -1.        ]
 [ 0.1571476   1.17962141  1.96143641  0.73712682 -0.64970024  1.        ]
 [-0.56058188  1.06263953  1.29098067 -0.540268   -0.0768146  -1.        ]
 [ 1.09209633 -1.48729335 -1.53741056  1.43803145 -0.18037147  1.        ]]


In [ ]:
#定義xy資料
weight_init = np.array([initial_weight]*6) #create the initial weight array
print(weight_init)
x0 = np.repeat([1], 10) #create the bias w0*x0 which w0 = bias, x0 = 1
print(x0)
#print(dataset[0,:-1])
dataset_new = np.c_[x0.T,dataset] #add bias(x0) inside the dataset
print(dataset_new) #there have 6 features(x0-x5) and one y 
y = dataset[:,-1] #get the true y

[0.5 0.5 0.5 0.5 0.5 0.5]
[1 1 1 1 1 1 1 1 1 1]
[[ 1.          1.35376718 -0.73229415 -0.87210827  0.4167009   0.03419463
   1.        ]
 [ 1.         -0.34823046 -0.17911861 -0.36049543 -0.27048646  0.1655967
  -1.        ]
 [ 1.          0.46549712 -0.76022261 -1.75218105 -1.71012837  0.94015988
  -1.        ]
 [ 1.          0.54476608  0.08702073  0.30319383  0.455433   -0.21725465
  -1.        ]
 [ 1.         -0.05787224 -0.81447809 -0.5810378   1.4476303  -0.37748363
   1.        ]
 [ 1.         -0.28995799  1.21599171  1.94815541  0.57322546 -0.59093697
   1.        ]
 [ 1.          0.37415928  1.25029887  1.60918821 -0.40738126 -0.18676714
  -1.        ]
 [ 1.          0.1571476   1.17962141  1.96143641  0.73712682 -0.64970024
   1.        ]
 [ 1.         -0.56058188  1.06263953  1.29098067 -0.540268   -0.0768146
  -1.        ]
 [ 1.          1.09209633 -1.48729335 -1.53741056  1.43803145 -0.18037147
   1.        ]]


In [ ]:
print(dataset_new[0,:-1])

[ 1.          1.35376718 -0.73229415 -0.87210827  0.4167009   0.03419463]


In [ ]:
weight = []
for j in range(0,10):
  for i in range(0,10):
    y_hat = sum(dataset_new[i,:-1]*weight_init.T)
    #判斷式
    if y_hat>= 0:
      y_hat = 1
    else:
      y_hat = -1
    print(i,y_hat)
    #更新後的weight
    weight_init = weight_init + l_rate*(y[i]-y_hat)*dataset_new[i,:-1]
    #print(weight_init)
  weight.append(weight_init)
print(i,weight)

0 1
1 1
2 -1
3 1
4 -1
5 1
6 1
7 1
8 -1
9 1
0 1
1 -1
2 -1
3 1
4 1
5 1
6 -1
7 1
8 -1
9 1
0 1
1 -1
2 -1
3 1
4 1
5 -1
6 1
7 1
8 -1
9 1
0 1
1 -1
2 -1
3 1
4 1
5 -1
6 1
7 -1
8 1
9 1
0 -1
1 -1
2 -1
3 1
4 1
5 -1
6 -1
7 1
8 -1
9 1
0 -1
1 -1
2 -1
3 1
4 1
5 1
6 -1
7 1
8 -1
9 1
0 1
1 -1
2 -1
3 1
4 1
5 -1
6 1
7 1
8 -1
9 1
0 -1
1 -1
2 -1
3 1
4 1
5 -1
6 -1
7 1
8 -1
9 1
0 1
1 -1
2 -1
3 1
4 1
5 1
6 -1
7 1
8 -1
9 1
0 -1
1 -1
2 -1
3 1
4 1
5 -1
6 -1
7 1
8 -1
9 1
9 [array([0.1       , 0.37428657, 0.10546418, 0.07341512, 0.834013  ,
       0.47218829]), array([-0.1       ,  0.26533335,  0.08806004,  0.01277635,  0.74292641,
        0.51563922]), array([-0.3       ,  0.02355668,  0.06379446,  0.01993103,  0.84796115,
        0.47825619]), array([-0.5       , -0.07467409,  0.06292526,  0.16117685,  1.20847486,
        0.32629602]), array([-0.3       ,  0.02913453,  0.14226062,  0.31574751,  1.31537353,
        0.25839849]), array([-0.3       ,  0.19093475, -0.02160235,  0.08068709,  1.30762711,
        0.30868

In [ ]:
weight_new = [np.round(num, 2) for num in weight]
print(weight_new)

[array([0.1 , 0.37, 0.11, 0.07, 0.83, 0.47]), array([-0.1 ,  0.27,  0.09,  0.01,  0.74,  0.52]), array([-0.3 ,  0.02,  0.06,  0.02,  0.85,  0.48]), array([-0.5 , -0.07,  0.06,  0.16,  1.21,  0.33]), array([-0.3 ,  0.03,  0.14,  0.32,  1.32,  0.26]), array([-0.3 ,  0.19, -0.02,  0.08,  1.31,  0.31]), array([-0.5 , -0.05, -0.05,  0.09,  1.41,  0.27]), array([-0.3 ,  0.05,  0.03,  0.24,  1.52,  0.2 ]), array([-0.5 , -0.06,  0.02,  0.18,  1.43,  0.25]), array([-0.3 ,  0.05,  0.1 ,  0.34,  1.54,  0.18])]


**Save your weight as csv**


Save your weights in each epoch in csv with name **student_id.csv** and should have same format as sample_submission.csv

In [ ]:
import numpy as np 
np.savetxt("r10521804.csv", weight_new, delimiter =",",fmt ='% s')